# Site settings
title: CI and CD with GitHub
description: A demo blog
email: yarmand@harakys.com
twitter_username: yarmand
github_username:  yarmand
baseurl:
url: https://githubteacher-ci-cd-workshop.herokuapp.com
destination: site_content
exclude: [ 'vendor' ]

# Build settings
markdown: kramdown
